import json
import torch
import torch.nn as nn
from sklearn.metrics import f1_score, roc_auc_score

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Phase 6.2: Task-Aware Dual-Matching Diffusion\n",
    "\n",
    "This notebook trains your Conditional 1D DDPM but adds a **Task-Aware Clinical Loss** term based on the TDD (2025) paper. \n",
    "It is optimized to use **Multiple GPUs via DataParallel** and includes the fixed evaluation code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader, TensorDataset\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import ast\n",
    "import requests\n",
    "import io\n",
    "import math\n",
    "from sklearn.model_selection import GroupShuffleSplit\n",
    "from sklearn.metrics import f1_score, roc_auc_score\n",
    "\n",
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "print(f\"Using device: {device}\")\n",
    "print(f\"Number of GPUs: {torch.cuda.device_count()}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 1. Load Data and Labels ---\n",
    "ptbxl_url = \"https://physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv\"\n",
    "scp_url = \"https://physionet.org/files/ptb-xl/1.0.3/scp_statements.csv\"\n",
    "ptbxl_df = pd.read_csv(io.StringIO(requests.get(ptbxl_url).text))\n",
    "scp_df = pd.read_csv(io.StringIO(requests.get(scp_url).text), index_col=0)\n",
    "\n",
    "def aggregate_diagnostic(y_dic):\n",
    "    tmp = []\n",
    "    for key in y_dic.keys():\n",
    "        if key in scp_df.index:\n",
    "            cls = scp_df.loc[key].diagnostic_class\n",
    "            if str(cls) != 'nan':\n",
    "                tmp.append(cls)\n",
    "    return list(set(tmp))\n",
    "\n",
    "ptbxl_df['scp_codes'] = ptbxl_df['scp_codes'].apply(lambda x: ast.literal_eval(x))\n",
    "ptbxl_df['diagnostic_superclass'] = ptbxl_df['scp_codes'].apply(aggregate_diagnostic)\n",
    "\n",
    "# Defaulting paths to current directory (Upload to Kaggle working dir or Kaggle dataset)\n",
    "metadata_path = 'metadata.csv' \n",
    "clean_path = 'clean_samples.npy'\n",
    "noisy_path = 'noisy_samples.npy'\n",
    "\n",
    "metadata = pd.read_csv(metadata_path)\n",
    "clean_all = np.load(clean_path)\n",
    "noisy_all = np.load(noisy_path)\n",
    "\n",
    "metadata['ecg_id_int'] = metadata['ecg_id'].astype(int)\n",
    "merged = metadata.merge(ptbxl_df[['ecg_id', 'diagnostic_superclass']], left_on='ecg_id_int', right_on='ecg_id', how='left')\n",
    "valid_indices = merged['diagnostic_superclass'].apply(lambda x: isinstance(x, list) and len(x) > 0)\n",
    "\n",
    "clean_filtered = clean_all[valid_indices]\n",
    "noisy_filtered = noisy_all[valid_indices]\n",
    "labels_raw = merged['diagnostic_superclass'][valid_indices].tolist()\n",
    "ecg_ids_filtered = merged['ecg_id_int'][valid_indices].values\n",
    "\n",
    "superclasses = ['NORM', 'MI', 'STTC', 'CD', 'HYP']\n",
    "y = np.zeros((len(labels_raw), 5))\n",
    "for i, labels in enumerate(labels_raw):\n",
    "    for j, sc in enumerate(superclasses):\n",
    "        if sc in labels:\n",
    "            y[i, j] = 1\n",
    "\n",
    "if len(clean_filtered.shape) == 2:\n",
    "    clean_filtered = np.expand_dims(clean_filtered, axis=1)\n",
    "    noisy_filtered = np.expand_dims(noisy_filtered, axis=1)\n",
    "\n",
    "# Use GroupShuffleSplit to prevent data leakage across leads of the same patient\n",
    "gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)\n",
    "train_idx, val_idx = next(gss.split(clean_filtered, y, groups=ecg_ids_filtered))\n",
    "\n",
    "X_train, X_val = clean_filtered[train_idx], clean_filtered[val_idx]\n",
    "cond_train, cond_val = noisy_filtered[train_idx], noisy_filtered[val_idx]\n",
    "y_train, y_val = y[train_idx], y[val_idx]\n",
    "\n",
    "print(f\"Training set: {X_train.shape[0]} samples\")\n",
    "print(f\"Validation set: {X_val.shape[0]} samples\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 2. Load the Frozen Oracle with DataParallel ---\n",
    "class ResNet1DBlock(nn.Module):\n",
    "    def __init__(self, in_channels, out_channels, stride=1):\n",
    "        super().__init__()\n",
    "        self.conv1 = nn.Conv1d(in_channels, out_channels, kernel_size=7, stride=stride, padding=3, bias=False)\n",
    "        self.bn1 = nn.BatchNorm1d(out_channels)\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "        self.conv2 = nn.Conv1d(out_channels, out_channels, kernel_size=7, stride=1, padding=3, bias=False)\n",
    "        self.bn2 = nn.BatchNorm1d(out_channels)\n",
    "        self.downsample = nn.Sequential(nn.Conv1d(in_channels, out_channels, 1, stride), nn.BatchNorm1d(out_channels)) if stride != 1 or in_channels != out_channels else nn.Identity()\n",
    "    def forward(self, x):\n",
    "        out = self.relu(self.bn1(self.conv1(x)))\n",
    "        out = self.bn2(self.conv2(out))\n",
    "        out += self.downsample(x)\n",
    "        return self.relu(out)\n",
    "\n",
    "class ResNet1D(nn.Module):\n",
    "    def __init__(self, num_classes=5):\n",
    "        super().__init__()\n",
    "        self.layer1 = nn.Sequential(nn.Conv1d(1, 32, 15, stride=2, padding=7), nn.BatchNorm1d(32), nn.ReLU(), nn.MaxPool1d(3, 2, 1))\n",
    "        self.layer2 = ResNet1DBlock(32, 64, stride=2)\n",
    "        self.layer3 = ResNet1DBlock(64, 128, stride=2)\n",
    "        self.layer4 = ResNet1DBlock(128, 256, stride=2)\n",
    "        self.layer5 = ResNet1DBlock(256, 512, stride=2)\n",
    "        self.pool = nn.AdaptiveAvgPool1d(1)\n",
    "        self.dropout = nn.Dropout(0.5)\n",
    "        self.fc = nn.Linear(512, num_classes)\n",
    "    def forward(self, x):\n",
    "        x = self.layer1(x)\n",
    "        x = self.layer2(x)\n",
    "        x = self.layer3(x)\n",
    "        x = self.layer4(x)\n",
    "        x = self.layer5(x)\n",
    "        x = self.pool(x).squeeze(-1)\n",
    "        x = self.dropout(x)\n",
    "        return self.fc(x)\n",
    "\n",
    "oracle = ResNet1D(num_classes=5)\n",
    "\n",
    "# Handle loading whether saved with DataParallel or not\n",
    "state_dict = torch.load('best_clinical_oracle.pth', map_location='cpu')\n",
    "if list(state_dict.keys())[0].startswith('module.'):\n",
    "    state_dict = {k.replace('module.', ''): v for k, v in state_dict.items()}\n",
    "oracle.load_state_dict(state_dict)\n",
    "\n",
    "if torch.cuda.device_count() > 1:\n",
    "    oracle = nn.DataParallel(oracle)\n",
    "\n",
    "oracle = oracle.to(device)\n",
    "oracle.eval()\n",
    "for param in oracle.parameters():\n",
    "    param.requires_grad = False  # Freeze the oracle\n",
    "print(\"Frozen Clinical Oracle Loaded & Moved to Device(s).\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 3. Diffusion Definitions ---\n",
    "class SinusoidalPositionEmbeddings(nn.Module):\n",
    "    def __init__(self, dim):\n",
    "        super().__init__()\n",
    "        self.dim = dim\n",
    "    def forward(self, time):\n",
    "        half_dim = self.dim // 2\n",
    "        embeddings = math.log(10000) / (half_dim - 1)\n",
    "        embeddings = torch.exp(torch.arange(half_dim, device=time.device) * -embeddings)\n",
    "        embeddings = time[:, None] * embeddings[None, :]\n",
    "        return torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)\n",
    "\n",
    "class Block1D(nn.Module):\n",
    "    def __init__(self, in_channels, out_channels, time_emb_dim):\n",
    "        super().__init__()\n",
    "        self.mlp = nn.Sequential(nn.SiLU(), nn.Linear(time_e
